
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SALON = 6;
  public static final int HORARIO = 8;
  public static final int ESTUDIANTEP = 12;
  public static final int ID = 19;
  public static final int COMILLAS = 18;
  public static final int ASIGNAR = 9;
  public static final int STRING = 20;
  public static final int COMA = 17;
  public static final int EOF = 0;
  public static final int EDIFICIO = 5;
  public static final int PUNTOC = 16;
  public static final int error = 1;
  public static final int NUMERO = 13;
  public static final int USUARIO = 2;
  public static final int ESTUDIANTE = 3;
  public static final int CATEDRATICO = 4;
  public static final int SUPER = 10;
  public static final int PARENTESISC = 15;
  public static final int COLABORADOR = 11;
  public static final int CURSO = 7;
  public static final int PARENTESISA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USUARIO",
  "ESTUDIANTE",
  "CATEDRATICO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIGNAR",
  "SUPER",
  "COLABORADOR",
  "ESTUDIANTEP",
  "NUMERO",
  "PARENTESISA",
  "PARENTESISC",
  "PUNTOC",
  "COMA",
  "COMILLAS",
  "ID",
  "STRING"
  };
}

